# -*- coding: utf-8 -*-
"""Traffic signal Estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3ssf4IZwr9y19UhjPEmpek-Orw3-AcR
"""

import cv2
import numpy as np
import random
import time
from google.colab.patches import cv2_imshow

# Create fake video window
width, height = 1280, 720

while True:
    # Create blank frame (road background)
    frame = np.zeros((height, width, 3), dtype=np.uint8)
    frame[:] = (50, 50, 50)  # road color

    # Draw lane divider
    cv2.line(frame, (640, 0), (640, 720), (255, 255, 255), 2)

    # Simulated vehicle counts (video-based assumption)
    left_count = random.randint(1, 10)
    right_count = random.randint(1, 10)
    total = left_count + right_count

    # Traffic density
    if total <= 5:
        density = "Low"
    elif total <= 12:
        density = "Medium"
    else:
        density = "High"

    # Signal decision
    if left_count > right_count:
        left_signal = "GREEN"
        right_signal = "RED"
    elif right_count > left_count:
        left_signal = "RED"
        right_signal = "GREEN"
    else:
        left_signal = "GREEN"
        right_signal = "GREEN"

    # Dashboard text
    cv2.putText(frame, f"Left Lane Count : {left_count}", (30, 40),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255,255,255), 2)
    cv2.putText(frame, f"Right Lane Count : {right_count}", (700, 40),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255,255,255), 2)

    cv2.putText(frame, f"Total Vehicles : {total}", (30, 90),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255,255,255), 2)
    cv2.putText(frame, f"Traffic Density : {density}", (30, 140),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0,255,255), 2)

    cv2.putText(frame, f"Left Signal : {left_signal}", (30, 190),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9,
                (0,255,0) if left_signal=="GREEN" else (0,0,255), 2)

    cv2.putText(frame, f"Right Signal : {right_signal}", (700, 190),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9,
                (0,255,0) if right_signal=="GREEN" else (0,0,255), 2)

    cv2_imshow(frame)

    time.sleep(1)  # simulate video frame delay

    if cv2.waitKey(1) & 0xFF == 27:
        break

cv2.destroyAllWindows()